#!/bin/bash
# Generated by incus-composer
# Generated at: 2024-01-01T01:39:34Z
# Generator version: 0.1.0
# Source hash: sha256:abc123def456_45

set -e  # Exit on any error

echo 'Starting incus-composer deployment...'

# ============================================
# Network Creation
# ============================================

echo 'Executing: incus network create cardiac --type=bridge'
incus network create cardiac --type=bridge
echo 'Executing: incus network set cardiac ipv4.address=10.10.10.1'
incus network set cardiac ipv4.address=10.10.10.1
echo 'Executing: incus network set cardiac ipv4.dhcp=false'
incus network set cardiac ipv4.dhcp=false
echo 'Executing: incus network create clinic --type=bridge'
incus network create clinic --type=bridge
echo 'Executing: incus network set clinic ipv4.address=192.168.11.1'
incus network set clinic ipv4.address=192.168.11.1
echo 'Executing: incus network set clinic ipv4.dhcp=false'
incus network set clinic ipv4.dhcp=false
echo 'Executing: incus network create hospital --type=bridge'
incus network create hospital --type=bridge
echo 'Executing: incus network set hospital ipv4.address=10.10.30.1'
incus network set hospital ipv4.address=10.10.30.1
echo 'Executing: incus network set hospital ipv4.dhcp=false'
incus network set hospital ipv4.dhcp=false
echo 'Executing: incus network create internet --type=bridge'
incus network create internet --type=bridge
echo 'Executing: incus network set internet ipv4.address=192.168.13.1'
incus network set internet ipv4.address=192.168.13.1
echo 'Executing: incus network set internet ipv4.dhcp=false'
incus network set internet ipv4.dhcp=false
echo 'Executing: incus network create monitor --type=bridge'
incus network create monitor --type=bridge
echo 'Executing: incus network set monitor ipv4.address=192.168.14.1'
incus network set monitor ipv4.address=192.168.14.1
echo 'Executing: incus network set monitor ipv4.dhcp=false'
incus network set monitor ipv4.dhcp=false
echo 'Executing: incus network create physician --type=bridge'
incus network create physician --type=bridge
echo 'Executing: incus network set physician ipv4.address=192.168.15.1'
incus network set physician ipv4.address=192.168.15.1
echo 'Executing: incus network set physician ipv4.dhcp=false'
incus network set physician ipv4.dhcp=false
echo 'Executing: incus network create server --type=bridge'
incus network create server --type=bridge
echo 'Executing: incus network set server ipv4.address=192.168.16.1'
incus network set server ipv4.address=192.168.16.1
echo 'Executing: incus network set server ipv4.dhcp=false'
incus network set server ipv4.dhcp=false

# ============================================
# Instance Creation and Configuration
# ============================================

echo 'Executing: incus create base_image oob --type=container'
incus create base_image oob --type=container
echo 'Executing: incus config set oob limits.cpu=2'
incus config set oob limits.cpu=2
echo 'Executing: incus config set oob limits.memory=2GB'
incus config set oob limits.memory=2GB
echo 'Executing: incus config device add oob eth0 nic network=bridge hwaddr=02:00:00:00:00:01'
incus config device add oob eth0 nic network=bridge hwaddr=02:00:00:00:00:01
echo 'Executing: incus start oob'
incus start oob
echo 'Executing: incus create base_image internet_firewall --type=container'
incus create base_image internet_firewall --type=container
echo 'Executing: incus config set internet_firewall limits.cpu=2'
incus config set internet_firewall limits.cpu=2
echo 'Executing: incus config set internet_firewall limits.memory=2GB'
incus config set internet_firewall limits.memory=2GB
echo 'Executing: incus config device add internet_firewall eth0 nic network=bridge hwaddr=02:00:00:00:00:02'
incus config device add internet_firewall eth0 nic network=bridge hwaddr=02:00:00:00:00:02
# Apply role 'router' to internet_firewall with values: []
echo 'Executing: incus start internet_firewall'
incus start internet_firewall
echo 'Executing: incus create base_image external_neuralert_server01 --type=container'
incus create base_image external_neuralert_server01 --type=container
echo 'Executing: incus config set external_neuralert_server01 limits.cpu=2'
incus config set external_neuralert_server01 limits.cpu=2
echo 'Executing: incus config set external_neuralert_server01 limits.memory=2GB'
incus config set external_neuralert_server01 limits.memory=2GB
echo 'Executing: incus config device add external_neuralert_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:03'
incus config device add external_neuralert_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:03
echo 'Executing: incus config device set external_neuralert_server01 eth0 ipv4.address=192.168.13.10'
incus config device set external_neuralert_server01 eth0 ipv4.address=192.168.13.10
# Apply role 'broker' to external_neuralert_server01 with values: []
# Apply role 'velociraptor' to external_neuralert_server01 with values: []
echo 'Executing: incus start external_neuralert_server01'
incus start external_neuralert_server01
echo 'Executing: incus create base_image external_vasowatch_server01 --type=container'
incus create base_image external_vasowatch_server01 --type=container
echo 'Executing: incus config set external_vasowatch_server01 limits.cpu=2'
incus config set external_vasowatch_server01 limits.cpu=2
echo 'Executing: incus config set external_vasowatch_server01 limits.memory=2GB'
incus config set external_vasowatch_server01 limits.memory=2GB
echo 'Executing: incus config device add external_vasowatch_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:04'
incus config device add external_vasowatch_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:04
echo 'Executing: incus config device set external_vasowatch_server01 eth0 ipv4.address=192.168.13.11'
incus config device set external_vasowatch_server01 eth0 ipv4.address=192.168.13.11
# Apply role 'velociraptor' to external_vasowatch_server01 with values: []
echo 'Executing: incus start external_vasowatch_server01'
incus start external_vasowatch_server01
echo 'Executing: incus create base_image external_sible_health_server01 --type=container'
incus create base_image external_sible_health_server01 --type=container
echo 'Executing: incus config set external_sible_health_server01 limits.cpu=2'
incus config set external_sible_health_server01 limits.cpu=2
echo 'Executing: incus config set external_sible_health_server01 limits.memory=2GB'
incus config set external_sible_health_server01 limits.memory=2GB
echo 'Executing: incus config device add external_sible_health_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:05'
incus config device add external_sible_health_server01 eth0 nic network=internet hwaddr=02:00:00:00:00:05
echo 'Executing: incus config device set external_sible_health_server01 eth0 ipv4.address=192.168.13.12'
incus config device set external_sible_health_server01 eth0 ipv4.address=192.168.13.12
# Apply role 'ssh' to external_sible_health_server01 with values: ["op_server0"]
# Apply role 'velociraptor' to external_sible_health_server01 with values: []
echo 'Executing: incus start external_sible_health_server01'
incus start external_sible_health_server01
echo 'Executing: incus create base_image external_physician_terminal01 --type=container'
incus create base_image external_physician_terminal01 --type=container
echo 'Executing: incus config set external_physician_terminal01 limits.cpu=2'
incus config set external_physician_terminal01 limits.cpu=2
echo 'Executing: incus config set external_physician_terminal01 limits.memory=2GB'
incus config set external_physician_terminal01 limits.memory=2GB
echo 'Executing: incus config device add external_physician_terminal01 eth0 nic network=internet hwaddr=02:00:00:00:00:06'
incus config device add external_physician_terminal01 eth0 nic network=internet hwaddr=02:00:00:00:00:06
echo 'Executing: incus config device set external_physician_terminal01 eth0 ipv4.address=192.168.13.13'
incus config device set external_physician_terminal01 eth0 ipv4.address=192.168.13.13
# Apply role 'velociraptor' to external_physician_terminal01 with values: []
echo 'Executing: incus start external_physician_terminal01'
incus start external_physician_terminal01
echo 'Executing: incus create base_image cardiac_router --type=container'
incus create base_image cardiac_router --type=container
echo 'Executing: incus config set cardiac_router limits.cpu=2'
incus config set cardiac_router limits.cpu=2
echo 'Executing: incus config set cardiac_router limits.memory=2GB'
incus config set cardiac_router limits.memory=2GB
echo 'Executing: incus config device add cardiac_router eth0 nic network=cardiac hwaddr=02:00:00:00:00:07'
incus config device add cardiac_router eth0 nic network=cardiac hwaddr=02:00:00:00:00:07
echo 'Executing: incus config device set cardiac_router eth0 ipv4.address=10.10.10.2'
incus config device set cardiac_router eth0 ipv4.address=10.10.10.2
echo 'Executing: incus config device add cardiac_router eth1 nic network=hospital'
incus config device add cardiac_router eth1 nic network=hospital
echo 'Executing: incus config device set cardiac_router eth1 ipv4.address=10.10.30.2'
incus config device set cardiac_router eth1 ipv4.address=10.10.30.2
# Apply role 'router' to cardiac_router with values: []
echo 'Executing: incus start cardiac_router'
incus start cardiac_router
echo 'Executing: incus create base_image patient01_monitor01 --type=container'
incus create base_image patient01_monitor01 --type=container
echo 'Executing: incus config set patient01_monitor01 limits.cpu=2'
incus config set patient01_monitor01 limits.cpu=2
echo 'Executing: incus config set patient01_monitor01 limits.memory=2GB'
incus config set patient01_monitor01 limits.memory=2GB
echo 'Executing: incus config device add patient01_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:08'
incus config device add patient01_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:08
echo 'Executing: incus config device set patient01_monitor01 eth0 ipv4.address=10.10.10.10'
incus config device set patient01_monitor01 eth0 ipv4.address=10.10.10.10
# Apply role 'velociraptor' to patient01_monitor01 with values: []
echo 'Executing: incus start patient01_monitor01'
incus start patient01_monitor01
echo 'Executing: incus create base_image patient01_monitor02 --type=container'
incus create base_image patient01_monitor02 --type=container
echo 'Executing: incus config set patient01_monitor02 limits.cpu=2'
incus config set patient01_monitor02 limits.cpu=2
echo 'Executing: incus config set patient01_monitor02 limits.memory=2GB'
incus config set patient01_monitor02 limits.memory=2GB
echo 'Executing: incus config device add patient01_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:09'
incus config device add patient01_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:09
echo 'Executing: incus config device set patient01_monitor02 eth0 ipv4.address=10.10.10.11'
incus config device set patient01_monitor02 eth0 ipv4.address=10.10.10.11
# Apply role 'velociraptor' to patient01_monitor02 with values: []
echo 'Executing: incus start patient01_monitor02'
incus start patient01_monitor02
echo 'Executing: incus create base_image patient02_monitor01 --type=container'
incus create base_image patient02_monitor01 --type=container
echo 'Executing: incus config set patient02_monitor01 limits.cpu=2'
incus config set patient02_monitor01 limits.cpu=2
echo 'Executing: incus config set patient02_monitor01 limits.memory=2GB'
incus config set patient02_monitor01 limits.memory=2GB
echo 'Executing: incus config device add patient02_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0a'
incus config device add patient02_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0a
echo 'Executing: incus config device set patient02_monitor01 eth0 ipv4.address=10.10.10.12'
incus config device set patient02_monitor01 eth0 ipv4.address=10.10.10.12
# Apply role 'velociraptor' to patient02_monitor01 with values: []
echo 'Executing: incus start patient02_monitor01'
incus start patient02_monitor01
echo 'Executing: incus create base_image patient02_monitor02 --type=container'
incus create base_image patient02_monitor02 --type=container
echo 'Executing: incus config set patient02_monitor02 limits.cpu=2'
incus config set patient02_monitor02 limits.cpu=2
echo 'Executing: incus config set patient02_monitor02 limits.memory=2GB'
incus config set patient02_monitor02 limits.memory=2GB
echo 'Executing: incus config device add patient02_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0b'
incus config device add patient02_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0b
echo 'Executing: incus config device set patient02_monitor02 eth0 ipv4.address=10.10.10.13'
incus config device set patient02_monitor02 eth0 ipv4.address=10.10.10.13
# Apply role 'velociraptor' to patient02_monitor02 with values: []
echo 'Executing: incus start patient02_monitor02'
incus start patient02_monitor02
echo 'Executing: incus create base_image patient03_monitor01 --type=container'
incus create base_image patient03_monitor01 --type=container
echo 'Executing: incus config set patient03_monitor01 limits.cpu=2'
incus config set patient03_monitor01 limits.cpu=2
echo 'Executing: incus config set patient03_monitor01 limits.memory=2GB'
incus config set patient03_monitor01 limits.memory=2GB
echo 'Executing: incus config device add patient03_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0c'
incus config device add patient03_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0c
echo 'Executing: incus config device set patient03_monitor01 eth0 ipv4.address=10.10.10.14'
incus config device set patient03_monitor01 eth0 ipv4.address=10.10.10.14
# Apply role 'velociraptor' to patient03_monitor01 with values: []
echo 'Executing: incus start patient03_monitor01'
incus start patient03_monitor01
echo 'Executing: incus create base_image patient03_monitor02 --type=container'
incus create base_image patient03_monitor02 --type=container
echo 'Executing: incus config set patient03_monitor02 limits.cpu=2'
incus config set patient03_monitor02 limits.cpu=2
echo 'Executing: incus config set patient03_monitor02 limits.memory=2GB'
incus config set patient03_monitor02 limits.memory=2GB
echo 'Executing: incus config device add patient03_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0d'
incus config device add patient03_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0d
echo 'Executing: incus config device set patient03_monitor02 eth0 ipv4.address=10.10.10.15'
incus config device set patient03_monitor02 eth0 ipv4.address=10.10.10.15
# Apply role 'velociraptor' to patient03_monitor02 with values: []
echo 'Executing: incus start patient03_monitor02'
incus start patient03_monitor02
echo 'Executing: incus create base_image patient04_monitor01 --type=container'
incus create base_image patient04_monitor01 --type=container
echo 'Executing: incus config set patient04_monitor01 limits.cpu=2'
incus config set patient04_monitor01 limits.cpu=2
echo 'Executing: incus config set patient04_monitor01 limits.memory=2GB'
incus config set patient04_monitor01 limits.memory=2GB
echo 'Executing: incus config device add patient04_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0e'
incus config device add patient04_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0e
echo 'Executing: incus config device set patient04_monitor01 eth0 ipv4.address=10.10.10.16'
incus config device set patient04_monitor01 eth0 ipv4.address=10.10.10.16
# Apply role 'velociraptor' to patient04_monitor01 with values: []
echo 'Executing: incus start patient04_monitor01'
incus start patient04_monitor01
echo 'Executing: incus create base_image patient04_monitor02 --type=container'
incus create base_image patient04_monitor02 --type=container
echo 'Executing: incus config set patient04_monitor02 limits.cpu=2'
incus config set patient04_monitor02 limits.cpu=2
echo 'Executing: incus config set patient04_monitor02 limits.memory=2GB'
incus config set patient04_monitor02 limits.memory=2GB
echo 'Executing: incus config device add patient04_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0f'
incus config device add patient04_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:0f
echo 'Executing: incus config device set patient04_monitor02 eth0 ipv4.address=10.10.10.17'
incus config device set patient04_monitor02 eth0 ipv4.address=10.10.10.17
# Apply role 'velociraptor' to patient04_monitor02 with values: []
echo 'Executing: incus start patient04_monitor02'
incus start patient04_monitor02
echo 'Executing: incus create base_image patient05_monitor01 --type=container'
incus create base_image patient05_monitor01 --type=container
echo 'Executing: incus config set patient05_monitor01 limits.cpu=2'
incus config set patient05_monitor01 limits.cpu=2
echo 'Executing: incus config set patient05_monitor01 limits.memory=2GB'
incus config set patient05_monitor01 limits.memory=2GB
echo 'Executing: incus config device add patient05_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:10'
incus config device add patient05_monitor01 eth0 nic network=cardiac hwaddr=02:00:00:00:00:10
echo 'Executing: incus config device set patient05_monitor01 eth0 ipv4.address=10.10.10.18'
incus config device set patient05_monitor01 eth0 ipv4.address=10.10.10.18
# Apply role 'velociraptor' to patient05_monitor01 with values: []
echo 'Executing: incus start patient05_monitor01'
incus start patient05_monitor01
echo 'Executing: incus create base_image patient05_monitor02 --type=container'
incus create base_image patient05_monitor02 --type=container
echo 'Executing: incus config set patient05_monitor02 limits.cpu=2'
incus config set patient05_monitor02 limits.cpu=2
echo 'Executing: incus config set patient05_monitor02 limits.memory=2GB'
incus config set patient05_monitor02 limits.memory=2GB
echo 'Executing: incus config device add patient05_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:11'
incus config device add patient05_monitor02 eth0 nic network=cardiac hwaddr=02:00:00:00:00:11
echo 'Executing: incus config device set patient05_monitor02 eth0 ipv4.address=10.10.10.19'
incus config device set patient05_monitor02 eth0 ipv4.address=10.10.10.19
# Apply role 'velociraptor' to patient05_monitor02 with values: []
echo 'Executing: incus start patient05_monitor02'
incus start patient05_monitor02
echo 'Executing: incus create base_image physician_router --type=container'
incus create base_image physician_router --type=container
echo 'Executing: incus config set physician_router limits.cpu=2'
incus config set physician_router limits.cpu=2
echo 'Executing: incus config set physician_router limits.memory=2GB'
incus config set physician_router limits.memory=2GB
echo 'Executing: incus config device add physician_router eth0 nic network=hospital hwaddr=02:00:00:00:00:12'
incus config device add physician_router eth0 nic network=hospital hwaddr=02:00:00:00:00:12
echo 'Executing: incus config device set physician_router eth0 ipv4.address=10.10.30.3'
incus config device set physician_router eth0 ipv4.address=10.10.30.3
echo 'Executing: incus config device add physician_router eth1 nic network=physician'
incus config device add physician_router eth1 nic network=physician
echo 'Executing: incus config device set physician_router eth1 ipv4.address=192.168.15.2'
incus config device set physician_router eth1 ipv4.address=192.168.15.2
# Apply role 'router' to physician_router with values: []
echo 'Executing: incus start physician_router'
incus start physician_router
echo 'Executing: incus create base_image nurse01_workstation01 --type=container'
incus create base_image nurse01_workstation01 --type=container
echo 'Executing: incus config set nurse01_workstation01 limits.cpu=2'
incus config set nurse01_workstation01 limits.cpu=2
echo 'Executing: incus config set nurse01_workstation01 limits.memory=2GB'
incus config set nurse01_workstation01 limits.memory=2GB
echo 'Executing: incus config device add nurse01_workstation01 eth0 nic network=physician hwaddr=02:00:00:00:00:13'
incus config device add nurse01_workstation01 eth0 nic network=physician hwaddr=02:00:00:00:00:13
echo 'Executing: incus config device set nurse01_workstation01 eth0 ipv4.address=192.168.15.10'
incus config device set nurse01_workstation01 eth0 ipv4.address=192.168.15.10
# Apply role 'subscriber' to nurse01_workstation01 with values: ["external_neuralert_server01"]
# Apply role 'velociraptor' to nurse01_workstation01 with values: []
echo 'Executing: incus start nurse01_workstation01'
incus start nurse01_workstation01
echo 'Executing: incus create base_image nurse01_workstation02 --type=container'
incus create base_image nurse01_workstation02 --type=container
echo 'Executing: incus config set nurse01_workstation02 limits.cpu=2'
incus config set nurse01_workstation02 limits.cpu=2
echo 'Executing: incus config set nurse01_workstation02 limits.memory=2GB'
incus config set nurse01_workstation02 limits.memory=2GB
echo 'Executing: incus config device add nurse01_workstation02 eth0 nic network=physician hwaddr=02:00:00:00:00:14'
incus config device add nurse01_workstation02 eth0 nic network=physician hwaddr=02:00:00:00:00:14
echo 'Executing: incus config device set nurse01_workstation02 eth0 ipv4.address=192.168.15.11'
incus config device set nurse01_workstation02 eth0 ipv4.address=192.168.15.11
# Apply role 'velociraptor' to nurse01_workstation02 with values: []
echo 'Executing: incus start nurse01_workstation02'
incus start nurse01_workstation02
echo 'Executing: incus create base_image nurse01_workstation03 --type=container'
incus create base_image nurse01_workstation03 --type=container
echo 'Executing: incus config set nurse01_workstation03 limits.cpu=2'
incus config set nurse01_workstation03 limits.cpu=2
echo 'Executing: incus config set nurse01_workstation03 limits.memory=2GB'
incus config set nurse01_workstation03 limits.memory=2GB
echo 'Executing: incus config device add nurse01_workstation03 eth0 nic network=physician hwaddr=02:00:00:00:00:15'
incus config device add nurse01_workstation03 eth0 nic network=physician hwaddr=02:00:00:00:00:15
echo 'Executing: incus config device set nurse01_workstation03 eth0 ipv4.address=192.168.15.12'
incus config device set nurse01_workstation03 eth0 ipv4.address=192.168.15.12
# Apply role 'velociraptor' to nurse01_workstation03 with values: []
echo 'Executing: incus start nurse01_workstation03'
incus start nurse01_workstation03
echo 'Executing: incus create base_image nurse01_tv01 --type=container'
incus create base_image nurse01_tv01 --type=container
echo 'Executing: incus config set nurse01_tv01 limits.cpu=2'
incus config set nurse01_tv01 limits.cpu=2
echo 'Executing: incus config set nurse01_tv01 limits.memory=2GB'
incus config set nurse01_tv01 limits.memory=2GB
echo 'Executing: incus config device add nurse01_tv01 eth0 nic network=physician hwaddr=02:00:00:00:00:16'
incus config device add nurse01_tv01 eth0 nic network=physician hwaddr=02:00:00:00:00:16
echo 'Executing: incus config device set nurse01_tv01 eth0 ipv4.address=192.168.15.13'
incus config device set nurse01_tv01 eth0 ipv4.address=192.168.15.13
# Apply role 'tv' to nurse01_tv01 with values: ["external_neuralert_server01"]
# Apply role 'velociraptor' to nurse01_tv01 with values: []
echo 'Executing: incus start nurse01_tv01'
incus start nurse01_tv01
echo 'Executing: incus create base_image physician01_terminal01 --type=container'
incus create base_image physician01_terminal01 --type=container
echo 'Executing: incus config set physician01_terminal01 limits.cpu=2'
incus config set physician01_terminal01 limits.cpu=2
echo 'Executing: incus config set physician01_terminal01 limits.memory=2GB'
incus config set physician01_terminal01 limits.memory=2GB
echo 'Executing: incus config device add physician01_terminal01 eth0 nic network=physician hwaddr=02:00:00:00:00:17'
incus config device add physician01_terminal01 eth0 nic network=physician hwaddr=02:00:00:00:00:17
echo 'Executing: incus config device set physician01_terminal01 eth0 ipv4.address=192.168.15.14'
incus config device set physician01_terminal01 eth0 ipv4.address=192.168.15.14
# Apply role 'pixi_base' to physician01_terminal01 with values: []
# Apply role 'velociraptor' to physician01_terminal01 with values: []
echo 'Executing: incus start physician01_terminal01'
incus start physician01_terminal01
echo 'Executing: incus create base_image physician01_terminal02 --type=container'
incus create base_image physician01_terminal02 --type=container
echo 'Executing: incus config set physician01_terminal02 limits.cpu=2'
incus config set physician01_terminal02 limits.cpu=2
echo 'Executing: incus config set physician01_terminal02 limits.memory=2GB'
incus config set physician01_terminal02 limits.memory=2GB
echo 'Executing: incus config device add physician01_terminal02 eth0 nic network=physician hwaddr=02:00:00:00:00:18'
incus config device add physician01_terminal02 eth0 nic network=physician hwaddr=02:00:00:00:00:18
echo 'Executing: incus config device set physician01_terminal02 eth0 ipv4.address=192.168.15.15'
incus config device set physician01_terminal02 eth0 ipv4.address=192.168.15.15
# Apply role 'pixi_base' to physician01_terminal02 with values: []
# Apply role 'velociraptor' to physician01_terminal02 with values: []
echo 'Executing: incus start physician01_terminal02'
incus start physician01_terminal02
echo 'Executing: incus create base_image server_router --type=container'
incus create base_image server_router --type=container
echo 'Executing: incus config set server_router limits.cpu=2'
incus config set server_router limits.cpu=2
echo 'Executing: incus config set server_router limits.memory=2GB'
incus config set server_router limits.memory=2GB
echo 'Executing: incus config device add server_router eth0 nic network=hospital hwaddr=02:00:00:00:00:19'
incus config device add server_router eth0 nic network=hospital hwaddr=02:00:00:00:00:19
echo 'Executing: incus config device set server_router eth0 ipv4.address=10.10.30.4'
incus config device set server_router eth0 ipv4.address=10.10.30.4
echo 'Executing: incus config device add server_router eth1 nic network=server'
incus config device add server_router eth1 nic network=server
echo 'Executing: incus config device set server_router eth1 ipv4.address=192.168.16.2'
incus config device set server_router eth1 ipv4.address=192.168.16.2
# Apply role 'router' to server_router with values: []
echo 'Executing: incus start server_router'
incus start server_router
echo 'Executing: incus create base_image internal_neuralert_server01 --type=container'
incus create base_image internal_neuralert_server01 --type=container
echo 'Executing: incus config set internal_neuralert_server01 limits.cpu=2'
incus config set internal_neuralert_server01 limits.cpu=2
echo 'Executing: incus config set internal_neuralert_server01 limits.memory=2GB'
incus config set internal_neuralert_server01 limits.memory=2GB
echo 'Executing: incus config device add internal_neuralert_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1a'
incus config device add internal_neuralert_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1a
echo 'Executing: incus config device set internal_neuralert_server01 eth0 ipv4.address=192.168.16.10'
incus config device set internal_neuralert_server01 eth0 ipv4.address=192.168.16.10
# Apply role 'velociraptor' to internal_neuralert_server01 with values: []
echo 'Executing: incus start internal_neuralert_server01'
incus start internal_neuralert_server01
echo 'Executing: incus create base_image internal_vasowatch_server01 --type=container'
incus create base_image internal_vasowatch_server01 --type=container
echo 'Executing: incus config set internal_vasowatch_server01 limits.cpu=2'
incus config set internal_vasowatch_server01 limits.cpu=2
echo 'Executing: incus config set internal_vasowatch_server01 limits.memory=2GB'
incus config set internal_vasowatch_server01 limits.memory=2GB
echo 'Executing: incus config device add internal_vasowatch_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1b'
incus config device add internal_vasowatch_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1b
echo 'Executing: incus config device set internal_vasowatch_server01 eth0 ipv4.address=192.168.16.11'
incus config device set internal_vasowatch_server01 eth0 ipv4.address=192.168.16.11
# Apply role 'velociraptor' to internal_vasowatch_server01 with values: []
echo 'Executing: incus start internal_vasowatch_server01'
incus start internal_vasowatch_server01
echo 'Executing: incus create base_image sibel_health_server01 --type=container'
incus create base_image sibel_health_server01 --type=container
echo 'Executing: incus config set sibel_health_server01 limits.cpu=2'
incus config set sibel_health_server01 limits.cpu=2
echo 'Executing: incus config set sibel_health_server01 limits.memory=2GB'
incus config set sibel_health_server01 limits.memory=2GB
echo 'Executing: incus config device add sibel_health_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1c'
incus config device add sibel_health_server01 eth0 nic network=server hwaddr=02:00:00:00:00:1c
echo 'Executing: incus config device set sibel_health_server01 eth0 ipv4.address=192.168.16.12'
incus config device set sibel_health_server01 eth0 ipv4.address=192.168.16.12
# Apply role 'velociraptor' to sibel_health_server01 with values: []
echo 'Executing: incus start sibel_health_server01'
incus start sibel_health_server01
echo 'Executing: incus create base_image monitor_router --type=container'
incus create base_image monitor_router --type=container
echo 'Executing: incus config set monitor_router limits.cpu=2'
incus config set monitor_router limits.cpu=2
echo 'Executing: incus config set monitor_router limits.memory=2GB'
incus config set monitor_router limits.memory=2GB
echo 'Executing: incus config device add monitor_router eth0 nic network=hospital hwaddr=02:00:00:00:00:1d'
incus config device add monitor_router eth0 nic network=hospital hwaddr=02:00:00:00:00:1d
echo 'Executing: incus config device set monitor_router eth0 ipv4.address=10.10.30.5'
incus config device set monitor_router eth0 ipv4.address=10.10.30.5
echo 'Executing: incus config device add monitor_router eth1 nic network=monitor'
incus config device add monitor_router eth1 nic network=monitor
echo 'Executing: incus config device set monitor_router eth1 ipv4.address=192.168.14.2'
incus config device set monitor_router eth1 ipv4.address=192.168.14.2
# Apply role 'router' to monitor_router with values: []
echo 'Executing: incus start monitor_router'
incus start monitor_router
echo 'Executing: incus create base_image emr_server01 --type=container'
incus create base_image emr_server01 --type=container
echo 'Executing: incus config set emr_server01 limits.cpu=2'
incus config set emr_server01 limits.cpu=2
echo 'Executing: incus config set emr_server01 limits.memory=2GB'
incus config set emr_server01 limits.memory=2GB
echo 'Executing: incus config device add emr_server01 eth0 nic network=monitor hwaddr=02:00:00:00:00:1e'
incus config device add emr_server01 eth0 nic network=monitor hwaddr=02:00:00:00:00:1e
echo 'Executing: incus config device set emr_server01 eth0 ipv4.address=192.168.14.10'
incus config device set emr_server01 eth0 ipv4.address=192.168.14.10
# Apply role 'velociraptor' to emr_server01 with values: []
echo 'Executing: incus start emr_server01'
incus start emr_server01
echo 'Executing: incus create base_image patient_monitor_server01 --type=container'
incus create base_image patient_monitor_server01 --type=container
echo 'Executing: incus config set patient_monitor_server01 limits.cpu=2'
incus config set patient_monitor_server01 limits.cpu=2
echo 'Executing: incus config set patient_monitor_server01 limits.memory=2GB'
incus config set patient_monitor_server01 limits.memory=2GB
echo 'Executing: incus config device add patient_monitor_server01 eth0 nic network=monitor hwaddr=02:00:00:00:00:1f'
incus config device add patient_monitor_server01 eth0 nic network=monitor hwaddr=02:00:00:00:00:1f
echo 'Executing: incus config device set patient_monitor_server01 eth0 ipv4.address=192.168.14.11'
incus config device set patient_monitor_server01 eth0 ipv4.address=192.168.14.11
# Apply role 'velociraptor' to patient_monitor_server01 with values: []
echo 'Executing: incus start patient_monitor_server01'
incus start patient_monitor_server01
echo 'Executing: incus create base_image clinic_router --type=container'
incus create base_image clinic_router --type=container
echo 'Executing: incus config set clinic_router limits.cpu=2'
incus config set clinic_router limits.cpu=2
echo 'Executing: incus config set clinic_router limits.memory=2GB'
incus config set clinic_router limits.memory=2GB
echo 'Executing: incus config device add clinic_router eth0 nic network=hospital hwaddr=02:00:00:00:00:20'
incus config device add clinic_router eth0 nic network=hospital hwaddr=02:00:00:00:00:20
echo 'Executing: incus config device set clinic_router eth0 ipv4.address=10.10.30.6'
incus config device set clinic_router eth0 ipv4.address=10.10.30.6
echo 'Executing: incus config device add clinic_router eth1 nic network=clinic'
incus config device add clinic_router eth1 nic network=clinic
echo 'Executing: incus config device set clinic_router eth1 ipv4.address=192.168.11.2'
incus config device set clinic_router eth1 ipv4.address=192.168.11.2
# Apply role 'router' to clinic_router with values: []
echo 'Executing: incus start clinic_router'
incus start clinic_router
echo 'Executing: incus create base_image ecg_pulse_oximeter01 --type=container'
incus create base_image ecg_pulse_oximeter01 --type=container
echo 'Executing: incus config set ecg_pulse_oximeter01 limits.cpu=2'
incus config set ecg_pulse_oximeter01 limits.cpu=2
echo 'Executing: incus config set ecg_pulse_oximeter01 limits.memory=2GB'
incus config set ecg_pulse_oximeter01 limits.memory=2GB
echo 'Executing: incus config device add ecg_pulse_oximeter01 eth0 nic network=clinic hwaddr=02:00:00:00:00:21'
incus config device add ecg_pulse_oximeter01 eth0 nic network=clinic hwaddr=02:00:00:00:00:21
echo 'Executing: incus config device set ecg_pulse_oximeter01 eth0 ipv4.address=192.168.11.10'
incus config device set ecg_pulse_oximeter01 eth0 ipv4.address=192.168.11.10
# Apply role 'velociraptor' to ecg_pulse_oximeter01 with values: []
echo 'Executing: incus start ecg_pulse_oximeter01'
incus start ecg_pulse_oximeter01
echo 'Executing: incus create base_image clinic_ipad01 --type=container'
incus create base_image clinic_ipad01 --type=container
echo 'Executing: incus config set clinic_ipad01 limits.cpu=2'
incus config set clinic_ipad01 limits.cpu=2
echo 'Executing: incus config set clinic_ipad01 limits.memory=2GB'
incus config set clinic_ipad01 limits.memory=2GB
echo 'Executing: incus config device add clinic_ipad01 eth0 nic network=clinic hwaddr=02:00:00:00:00:22'
incus config device add clinic_ipad01 eth0 nic network=clinic hwaddr=02:00:00:00:00:22
echo 'Executing: incus config device set clinic_ipad01 eth0 ipv4.address=192.168.11.11'
incus config device set clinic_ipad01 eth0 ipv4.address=192.168.11.11
# Apply role 'velociraptor' to clinic_ipad01 with values: []
echo 'Executing: incus start clinic_ipad01'
incus start clinic_ipad01
echo 'Executing: incus create base_image patient_bed01 --type=container'
incus create base_image patient_bed01 --type=container
echo 'Executing: incus config set patient_bed01 limits.cpu=2'
incus config set patient_bed01 limits.cpu=2
echo 'Executing: incus config set patient_bed01 limits.memory=2GB'
incus config set patient_bed01 limits.memory=2GB
echo 'Executing: incus config device add patient_bed01 eth0 nic network=clinic hwaddr=02:00:00:00:00:23'
incus config device add patient_bed01 eth0 nic network=clinic hwaddr=02:00:00:00:00:23
echo 'Executing: incus config device set patient_bed01 eth0 ipv4.address=192.168.11.12'
incus config device set patient_bed01 eth0 ipv4.address=192.168.11.12
# Apply role 'neuralert_device' to patient_bed01 with values: ["external_neuralert_server01"]
# Apply role 'patient_monitor' to patient_bed01 with values: []
# Apply role 'velociraptor' to patient_bed01 with values: []
echo 'Executing: incus start patient_bed01'
incus start patient_bed01
echo 'Executing: incus create base_image patient_bed02 --type=container'
incus create base_image patient_bed02 --type=container
echo 'Executing: incus config set patient_bed02 limits.cpu=2'
incus config set patient_bed02 limits.cpu=2
echo 'Executing: incus config set patient_bed02 limits.memory=2GB'
incus config set patient_bed02 limits.memory=2GB
echo 'Executing: incus config device add patient_bed02 eth0 nic network=clinic hwaddr=02:00:00:00:00:24'
incus config device add patient_bed02 eth0 nic network=clinic hwaddr=02:00:00:00:00:24
echo 'Executing: incus config device set patient_bed02 eth0 ipv4.address=192.168.11.13'
incus config device set patient_bed02 eth0 ipv4.address=192.168.11.13
# Apply role 'neuralert_device' to patient_bed02 with values: ["external_neuralert_server01"]
# Apply role 'patient_monitor' to patient_bed02 with values: []
# Apply role 'velociraptor' to patient_bed02 with values: []
echo 'Executing: incus start patient_bed02'
incus start patient_bed02
echo 'Executing: incus create base_image patient_bed03 --type=container'
incus create base_image patient_bed03 --type=container
echo 'Executing: incus config set patient_bed03 limits.cpu=2'
incus config set patient_bed03 limits.cpu=2
echo 'Executing: incus config set patient_bed03 limits.memory=2GB'
incus config set patient_bed03 limits.memory=2GB
echo 'Executing: incus config device add patient_bed03 eth0 nic network=clinic hwaddr=02:00:00:00:00:25'
incus config device add patient_bed03 eth0 nic network=clinic hwaddr=02:00:00:00:00:25
echo 'Executing: incus config device set patient_bed03 eth0 ipv4.address=192.168.11.14'
incus config device set patient_bed03 eth0 ipv4.address=192.168.11.14
# Apply role 'neuralert_device' to patient_bed03 with values: ["external_neuralert_server01"]
# Apply role 'patient_monitor' to patient_bed03 with values: []
# Apply role 'velociraptor' to patient_bed03 with values: []
echo 'Executing: incus start patient_bed03'
incus start patient_bed03
echo 'Executing: incus create base_image patient_bed04 --type=container'
incus create base_image patient_bed04 --type=container
echo 'Executing: incus config set patient_bed04 limits.cpu=2'
incus config set patient_bed04 limits.cpu=2
echo 'Executing: incus config set patient_bed04 limits.memory=2GB'
incus config set patient_bed04 limits.memory=2GB
echo 'Executing: incus config device add patient_bed04 eth0 nic network=clinic hwaddr=02:00:00:00:00:26'
incus config device add patient_bed04 eth0 nic network=clinic hwaddr=02:00:00:00:00:26
echo 'Executing: incus config device set patient_bed04 eth0 ipv4.address=192.168.11.15'
incus config device set patient_bed04 eth0 ipv4.address=192.168.11.15
# Apply role 'neuralert_device' to patient_bed04 with values: ["external_neuralert_server01"]
# Apply role 'patient_monitor' to patient_bed04 with values: []
# Apply role 'velociraptor' to patient_bed04 with values: []
echo 'Executing: incus start patient_bed04'
incus start patient_bed04

echo 'Deployment completed successfully!'